### PR TITLE
some namespace changes

### PR DESCRIPTION
**Pull request by Fosphatic**

### CODE REVIEW

**Comment by ynswtf** [comment]
Can you give me time to review? Thank you my friend for helps :+1:  :1st_place_medal:

**Comment by Fosphatic** [comment]
No problem glad i could figure it myself out. :) I tested the code change it seems to work smooth now beside the original blog extension, was even able to uninstall the original blog and install it again without any errors! Well still long way to go. 👍

**Comment by ynswtf** [comment]
I can merge at this night your pull request. Thank you

**Comment by Fosphatic** [comment]
I guess you worked on the login plugin all night huh?

**Comment by ynswtf** [comment]
Yes I am tired at night

**Pull request merged**
